name: Windows GUI Release
on: [push, pull_request, workflow_dispatch]

    
            
env:
  QT_VERSION: "6.10.1"
  SOURCE_DIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
               
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.3.*'
        version: ${{env.QT_VERSION}}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        install-deps: true
        dir: "${{env.SOURCE_DIR}}/qt"
