name: Windows GUI Release
on: [pull_request]

    
            
env:
  QT_VERSION: "6.10.1"
  SOURCE_DIR: ${{ github.workspace }}
  BUILD_TYPE: Release
  BUILD_FOLDER: "${{ github.workspace }}/build"
defaults:
  run:
   shell: pwsh

jobs:
  build:
    runs-on: windows-2025
    

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Create dir
      run: |
        mkdir ${{env.BUILD_FOLDER}}

               
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.3.*'
        version: '6.10.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        install-deps: true
        dir: "${{env.SOURCE_DIR}}/qt"
        cache: true
        modules: 'qt5compat'


    - name: Configure CMake Project
      run: |
        cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build project
      run: cmake --build ${{env.BUILD_FOLDER}} --config ${{ env.BUILD_TYPE }}
      
    - name: Analyse QML
      shell: powershell
      run: |
        Get-ChildItem -Path "${{ github.workspace }}/SongImporterGui" -Recurse -Filter *.qml | ForEach-Object {
          Write-Host "Linting $($_.FullName)"
          qmllint $_.FullName
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        }
