name: Windows GUI Release
on: [push, pull_request, workflow_dispatch]

    
            
env:
  QT_VERSION: "6.10.1"
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.11"
        
    - name: Install Qt 6.10.1 (MinGW)
      run: |
          python -m pip install --upgrade pip
          pip install aqtinstall

          aqt install-qt windows desktop 6.10.1 win64_mingw -O C:\Qt
          
    - name: Setup Qt environment
      shell: powershell
      run: |
          echo "C:\Qt\6.10.1\mingw_64\bin" >> $env:GITHUB_PATH
          echo "C:\Qt\Tools\mingw1310_64\bin" >> $env:GITHUB_PATH
