name: Windows Deployment
on:
  pull_request:
    branches:
      - main
      # keep this for now
      - dev

jobs:
 build:
   uses: ./.github/workflows/main.yml
 deploy:
  needs: build
  runs-on: windows-2025
  steps:
   - name: "Make deploy folder"
     run: |
       mkdir deploy
       ls ${{needs.build.outputs.build_folder}}
    # Move-Item -Path ${{needs.build.outputs.build_folder}}/SongImporterGui/${{needs.build.outputs.build_type}}/appSongImporterGui.exe -Destination ./deploy/appSongImporterGui.exe
